// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package models

import (
	"time"
)

type Menu struct {
	ID                 int32
	NameProduct        string
	Price              int64
	DescriptionProduct string
	ImageProduct       string
	StockProduct       int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}
